import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { ThemeProvider } from "@/providers/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang="en" suppressHydrationWarning>
        <head></head>
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}



// 'use client';

// import { useEffect, useState } from "react";
// import "./globals.css";
// import { Inter } from "next/font/google";
// import { ClerkProvider } from "@clerk/nextjs";
// import { dark } from "@clerk/themes";
// import { ThemeProvider } from "@/providers/theme-provider";

// const inter = Inter({ subsets: ["latin"] });

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   const [isHydrated, setIsHydrated] = useState(false);

//   useEffect(() => {
//     setIsHydrated(true);
//   }, []);

//   if (!isHydrated) {
//     return null; // Avoid mismatches by not rendering until hydration
//   }

//   return (
//     <ClerkProvider appearance={{ baseTheme: dark }}>
//       <html lang="en" suppressHydrationWarning>
//         <body className={inter.className}>
//           <ThemeProvider
//             attribute="class"
//             defaultTheme="light"
//             enableSystem
//             disableTransitionOnChange
//           >
//             {children}
//           </ThemeProvider>
//         </body>
//       </html>
//     </ClerkProvider>
//   );
// }



// 'use client';

// import { useEffect, useState } from "react";
// import Head from "next/head";
// import "./globals.css";
// import { Inter } from "next/font/google";
// import { ClerkProvider } from "@clerk/nextjs";
// import { dark } from "@clerk/themes";
// import { ThemeProvider } from "@/providers/theme-provider";

// const inter = Inter({ subsets: ["latin"] });

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   const [isHydrated, setIsHydrated] = useState(false);

//   useEffect(() => {
//     setIsHydrated(true);
//   }, []);

//   if (!isHydrated) {
//     return null; // Avoid mismatches by not rendering until hydration
//   }

//   return (
//     <ClerkProvider appearance={{ baseTheme: dark }}>
//       <html lang="en" suppressHydrationWarning>
//         <head>
//           <title>Create Next App</title>
//           <meta name="description" content="Generated by create next app" />
//           <meta name="viewport" content="width=device-width, initial-scale=1" />
//         </head>
//         <body className={inter.className}>
//           <ThemeProvider
//             attribute="class"
//             defaultTheme="light"
//             enableSystem
//             disableTransitionOnChange
//           >
//             {children}
//           </ThemeProvider>
//         </body>
//       </html>
//     </ClerkProvider>
//   );
// }
